/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_com_motinlu_mt_ndk_serialPortApi_SerialPort
#define _Included_com_motinlu_mt_ndk_serialPortApi_SerialPort
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_serialPortApi_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_serialPortApi_SerialPort_close
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_serialPortApi_stringFromJNISP(
        JNIEnv *env,
        jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
